export const selectors = [
  "body",
  "default--div",
  "default--heading",
  "default--paragraph",
  "rating--list",
  "star--div",
  "star--img",
  "submit--button",
  "active--div",
  "thank--image",
  "selected--paragraph",
  "active--heading",
  "thank--paragraph",
];
